### ISSUE TITLE
wrong temp file name

### ISSUE THREAD

**Issue by Pjack** [antespi/s3md5#6]
Should use double quote or cannot get the process id.
It may cause trouble during multi-thread condition.

ERROR_FILE='/tmp/s3md5-error-$$.out'
SUM_FILE='/tmp/s3md5-md5sumlist-$$.out'
BIN_FILE='/tmp/s3md5-md5bin-$$.out'

=>

ERROR_FILE="/tmp/s3md5-error-$$.out"
SUM_FILE="/tmp/s3md5-md5sumlist-$$.out"
BIN_FILE="/tmp/s3md5-md5bin-$$.out"

**Comment by antespi** [comment]
Fixed at https://github.com/antespi/s3md5/commit/fc6fdf4a862227c2dc281961ddd9706da99a8ad1
Thanks @Pjack
